// Dados dos produtos para uso na página de produto
export const products = {
  "quadro-familia": {
    id: 1,
    slug: "quadro-familia",
    name: "Quadro Família - É um presente de Deus",
    price: 89.9,
    oldPrice: 109.9,
    discount: 18,
    rating: 5,
    reviewCount: 12,
    stock: 15,
    description:
      "Quadro decorativo com a mensagem 'A nossa família é um presente de Deus, repleto de amor'. Perfeito para decorar sua casa com fé e espiritualidade.",
    details: "Feito em MDF de alta qualidade com acabamento premium. Inclui suporte para fixação na parede.",
    dimensions: "25cm x 20cm x 2cm",
    material: "MDF e papel fotográfico",
    weight: "0.5kg",
    sku: "QF-001",
    categories: ["decoracao", "presentes"],
    collections: ["familia"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: ["Mensagem inspiradora", "Design elegante", "Fácil instalação", "Acabamento de alta qualidade"],
  },
  "terco-madeira": {
    id: 2,
    slug: "terco-madeira",
    name: "Terço de Madeira com Medalha",
    price: 45.5,
    oldPrice: 55.9,
    discount: 19,
    rating: 4.8,
    reviewCount: 24,
    stock: 8,
    description:
      "Terço de madeira artesanal com medalha de São Miguel Arcanjo. Ideal para orações diárias e como presente para ocasiões especiais.",
    details:
      "Confeccionado com contas de madeira natural e cordão resistente. Acompanha medalha banhada em prata envelhecida.",
    dimensions: "45cm de comprimento",
    material: "Madeira e metal",
    weight: "0.1kg",
    sku: "TM-002",
    categories: ["tercos", "presentes"],
    collections: ["nossa-senhora"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: [
      "Contas de madeira natural",
      "Medalha de São Miguel Arcanjo",
      "Acabamento artesanal",
      "Cordão resistente",
    ],
  },
  "imagem-sagrada-familia": {
    id: 3,
    slug: "imagem-sagrada-familia",
    name: "Imagem Sagrada Família",
    price: 120.0,
    oldPrice: 150.0,
    discount: 20,
    rating: 4.9,
    reviewCount: 18,
    stock: 10,
    description:
      "Imagem decorativa da Sagrada Família, representando Jesus, Maria e José. Uma peça de arte sacra para trazer paz e espiritualidade ao seu lar.",
    details:
      "Esculpida em resina de alta qualidade com acabamento pintado à mão. Base estável para apoio em superfícies planas.",
    dimensions: "20cm x 15cm x 8cm",
    material: "Resina",
    weight: "0.8kg",
    sku: "SF-003",
    categories: ["imagens", "decoracao"],
    collections: ["sagrada-familia"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: [
      "Detalhes realistas",
      "Acabamento pintado à mão",
      "Base estável",
      "Material durável",
      "Ideal para presentes",
    ],
  },
  "divino-espirito-santo": {
    id: 4,
    slug: "divino-espirito-santo",
    name: "Divino Espírito Santo Decorativo",
    price: 75.9,
    oldPrice: 89.9,
    discount: 15,
    rating: 4.7,
    reviewCount: 14,
    stock: 12,
    description:
      "Divino Espírito Santo decorativo para parede, símbolo de paz, sabedoria e inspiração. Ideal para decorar sua casa com fé e elegância.",
    details: "Confeccionado em madeira com acabamento em pintura especial. Inclui suporte para fixação na parede.",
    dimensions: "30cm x 25cm x 3cm",
    material: "Madeira",
    weight: "0.4kg",
    sku: "DES-004",
    categories: ["decoracao"],
    collections: ["divino-espirito-santo"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: ["Design tradicional", "Acabamento artesanal", "Fácil instalação", "Símbolo de proteção"],
  },
  "quadro-nossa-senhora": {
    id: 5,
    slug: "quadro-nossa-senhora",
    name: "Quadro Nossa Senhora",
    price: 95.0,
    oldPrice: 115.0,
    discount: 17,
    rating: 4.8,
    reviewCount: 22,
    stock: 8,
    description:
      "Quadro decorativo com a imagem de Nossa Senhora das Graças. Uma peça de arte sacra para trazer proteção e bênçãos ao seu lar.",
    details: "Impresso em canvas de alta qualidade com moldura em madeira. Pronto para pendurar.",
    dimensions: "40cm x 30cm x 2cm",
    material: "Canvas e madeira",
    weight: "0.6kg",
    sku: "QNS-005",
    categories: ["decoracao", "presentes"],
    collections: ["nossa-senhora"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: ["Imagem de alta definição", "Moldura elegante", "Pronto para pendurar", "Cores vibrantes"],
  },
  "terco-parede": {
    id: 6,
    slug: "terco-parede",
    name: "Terço de Parede Decorativo",
    price: 65.9,
    oldPrice: 79.9,
    discount: 18,
    rating: 4.6,
    reviewCount: 16,
    stock: 15,
    description:
      "Terço decorativo para parede, uma peça única que combina fé e decoração. Ideal para sala de estar, quarto ou espaço de oração.",
    details:
      "Confeccionado com contas de madeira grandes e cordão resistente. Inclui crucifixo detalhado e suporte para fixação.",
    dimensions: "80cm de comprimento",
    material: "Madeira e cordão",
    weight: "0.3kg",
    sku: "TP-006",
    categories: ["tercos", "decoracao"],
    collections: ["nossa-senhora"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: ["Contas grandes", "Crucifixo detalhado", "Fácil instalação", "Design exclusivo"],
  },
  "biblia-capa-especial": {
    id: 7,
    slug: "biblia-capa-especial",
    name: "Bíblia Sagrada Capa Especial",
    price: 110.0,
    oldPrice: 135.0,
    discount: 19,
    rating: 4.9,
    reviewCount: 28,
    stock: 10,
    description:
      "Bíblia Sagrada com capa especial em couro sintético e acabamento premium. Edição com letras grandes e marcador de páginas.",
    details:
      "Edição completa com Antigo e Novo Testamento, notas explicativas e mapas coloridos. Inclui marcador de páginas em cetim.",
    dimensions: "23cm x 16cm x 4cm",
    material: "Papel bíblia e capa em couro sintético",
    weight: "0.9kg",
    sku: "BS-007",
    categories: ["livros"],
    collections: [],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: [
      "Letras grandes para fácil leitura",
      "Capa durável em couro sintético",
      "Marcador de páginas em cetim",
      "Mapas coloridos",
      "Notas explicativas",
    ],
  },
  "crucifixo-parede": {
    id: 8,
    slug: "crucifixo-parede",
    name: "Crucifixo de Parede",
    price: 55.9,
    oldPrice: 69.9,
    discount: 20,
    rating: 4.7,
    reviewCount: 19,
    stock: 14,
    description:
      "Crucifixo de parede em madeira com detalhes em bronze. Uma peça tradicional para trazer proteção e fé ao seu lar.",
    details:
      "Confeccionado em madeira nobre com acabamento em verniz e detalhes em bronze. Inclui suporte para fixação na parede.",
    dimensions: "35cm x 20cm x 3cm",
    material: "Madeira e bronze",
    weight: "0.4kg",
    sku: "CP-008",
    categories: ["decoracao"],
    collections: [],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: ["Madeira nobre", "Detalhes em bronze", "Acabamento em verniz", "Fácil instalação"],
  },
  "familia-pouso-seguro": {
    id: 9,
    slug: "familia-pouso-seguro",
    name: "Família é lugar de Pouso seguro",
    price: 79.9,
    oldPrice: 95.0,
    discount: 16,
    rating: 4.8,
    reviewCount: 15,
    stock: 12,
    description:
      "Um lindo quadro de madeira decorativo com a frase 'Família é lugar de Pouso seguro, Aconchego e amor!'.",
    details: "Confeccionado em MDF de alta qualidade com impressão direta e acabamento em verniz protetor.",
    dimensions: "30cm x 20cm x 2cm",
    material: "MDF",
    weight: "0.5kg",
    sku: "FPS-009",
    categories: ["decoracao", "familia"],
    collections: ["familia"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: ["Mensagem inspiradora", "Design moderno", "Fácil instalação", "Acabamento em verniz protetor"],
  },
  "familia-projeto-deus": {
    id: 10,
    slug: "familia-projeto-deus",
    name: "Família é um projeto de Deus",
    price: 85.0,
    oldPrice: 99.9,
    discount: 15,
    rating: 4.9,
    reviewCount: 17,
    stock: 10,
    description:
      "Um lindo quadro de madeira decorativo com a frase 'Família é um PROJETO de Deus, para refletir seu amor e cuidado por todos nós!'.",
    details: "Confeccionado em MDF de alta qualidade com impressão direta e acabamento em verniz protetor.",
    dimensions: "30cm x 20cm x 2cm",
    material: "MDF",
    weight: "0.5kg",
    sku: "FPD-010",
    categories: ["decoracao", "familia"],
    collections: ["familia"],
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    features: ["Mensagem inspiradora", "Design moderno", "Fácil instalação", "Acabamento em verniz protetor"],
  },
}

