// Dados dos produtos para uso na página de produto
export const products = {
  "imagem-sagrada-familia-dourada": {
    id: 1,
    slug: "imagem-sagrada-familia-dourada",
    name: "Imagem Sagrada Família em Porcelana com Detalhes Dourados",
    price: 135.0,
    oldPrice: 159.9,
    discount: 16,
    rating: 5.0,
    reviewCount: 8,
    stock: 5,
    description:
      "Belíssima imagem da Sagrada Família em porcelana branca com detalhes dourados. Uma peça elegante e refinada para decorar seu lar com fé e espiritualidade.",
    details:
      "Confeccionada em porcelana de alta qualidade com acabamentos dourados aplicados à mão. Base estável para apoio em superfícies planas.",
    dimensions: "22cm x 15cm x 8cm",
    material: "Porcelana com detalhes em dourado",
    weight: "0.7kg",
    sku: "SFD-019",
    categories: ["imagens", "decoracao"],
    collections: ["sagrada-familia"],
    images: [
      "https://maededeus.vercel.app/public/imagem-sagrada-familia-dourada.jpg",
      "https://maededeus.vercel.app/public/imagem-sagrada-familia-dourada.jpg",
    ],
    features: [
      "Porcelana de alta qualidade",
      "Detalhes dourados aplicados à mão",
      "Design elegante e refinado",
      "Base estável",
      "Ideal para decoração e presentes especiais",
    ],
  },
  "conjunto-nossa-senhora-azul": {
    id: 2,
    slug: "conjunto-nossa-senhora-azul",
    name: "Conjunto Nossa Senhora das Graças Azul",
    price: 120.0,
    oldPrice: 145.0,
    discount: 17,
    rating: 4.9,
    reviewCount: 12,
    stock: 7,
    description:
      "Lindo conjunto decorativo em tons de azul e branco, incluindo imagem de Nossa Senhora das Graças, pomba do Divino Espírito Santo e medalha decorativa.",
    details:
      "Conjunto confeccionado em porcelana com acabamento em esmalte azul e branco. Peças vendidas em conjunto, ideais para decorar ambientes com harmonia e fé.",
    dimensions: "Nossa Senhora: 18cm x 8cm x 5cm, Pomba: 10cm x 8cm x 4cm, Medalha: 8cm de diâmetro",
    material: "Porcelana esmaltada",
    weight: "0.9kg (conjunto completo)",
    sku: "NSA-020",
    categories: ["imagens", "decoracao"],
    collections: ["nossa-senhora", "espirito-santo"],
    images: [
      "https://maededeus.vercel.app/public/conjunto-nossa-senhora-azul.jpg",
      "https://maededeus.vercel.app/public/conjunto-nossa-senhora-azul.jpg",
    ],
    features: [
      "Conjunto completo com 3 peças",
      "Acabamento em esmalte azul e branco",
      "Design harmonioso",
      "Peças complementares entre si",
      "Ideal para decoração de ambientes religiosos",
    ],
  },
  "caneca-voce-e-luz": {
    id: 3,
    slug: "caneca-voce-e-luz",
    name: "Caneca Porcelana - Você é Luz",
    price: 39.9,
    oldPrice: 49.9,
    discount: 20,
    rating: 4.8,
    reviewCount: 15,
    stock: 20,
    description:
      "Caneca de porcelana com a mensagem inspiradora 'Você é luz por onde passa!'. Perfeita para presentear alguém especial ou para trazer mais inspiração ao seu dia a dia.",
    details:
      "Caneca de porcelana de alta qualidade com impressão durável e resistente a microondas e lava-louças. Acompanha embalagem para presente.",
    dimensions: "9,5cm de altura x 8cm de diâmetro",
    material: "Porcelana",
    weight: "0.3kg",
    sku: "CVL-021",
    categories: ["utilidades", "presentes"],
    collections: ["canecas"],
    images: [
      "https://maededeus.vercel.app/public/caneca-voce-e-luz.jpg",
      "https://maededeus.vercel.app/public/caneca-voce-e-luz.jpg",
    ],
    features: [
      "Porcelana de alta qualidade",
      "Impressão durável",
      "Resistente a microondas e lava-louças",
      "Mensagem inspiradora",
      "Acompanha embalagem para presente",
    ],
  },
  "divino-mandala": {
    id: 4,
    slug: "divino-mandala",
    name: "Divino Espírito Santo Mandala Decorativo",
    price: 105.0,
    oldPrice: 129.9,
    discount: 19,
    rating: 4.9,
    reviewCount: 10,
    stock: 8,
    description:
      "Elegante decoração de parede em formato de mandala com o Divino Espírito Santo ao centro. Uma peça única que combina espiritualidade e design contemporâneo.",
    details:
      "Confeccionado em metal com acabamento dourado e detalhes em branco. Inclui suporte para fixação na parede.",
    dimensions: "40cm de diâmetro x 3cm de profundidade",
    material: "Metal com acabamento dourado",
    weight: "0.8kg",
    sku: "DEM-022",
    categories: ["decoracao", "divino-espirito-santo"],
    collections: ["divino-espirito-santo"],
    images: [
      "https://maededeus.vercel.app/public/divino-espirito-santo-mandala.jpg",
      "https://maededeus.vercel.app/public/divino-espirito-santo-mandala.jpg",
    ],
    features: [
      "Design exclusivo em formato de mandala",
      "Acabamento dourado premium",
      "Fácil instalação",
      "Peça decorativa de alto impacto visual",
      "Símbolo de proteção e sabedoria",
    ],
  },
  "conjunto-anjos": {
    id: 5,
    slug: "conjunto-anjos",
    name: "Conjunto Anjos Decorativos",
    price: 65.0,
    oldPrice: 79.9,
    discount: 19,
    rating: 4.7,
    reviewCount: 14,
    stock: 12,
    description:
      "Encantador conjunto de anjos decorativos em diferentes cores e estilos. Perfeitos para decorar ambientes infantis, quartos ou espaços de oração.",
    details:
      "Conjunto com 3 anjos em resina com acabamento em diferentes cores (branco, rosa e azul). Peças vendidas em conjunto.",
    dimensions: "Aproximadamente 12cm de altura cada",
    material: "Resina",
    weight: "0.6kg (conjunto completo)",
    sku: "CAD-023",
    categories: ["decoracao", "anjos"],
    collections: ["anjos"],
    images: [
      "https://maededeus.vercel.app/public/conjunto-anjos-decorativos.jpg",
      "https://maededeus.vercel.app/public/conjunto-anjos-decorativos.jpg",
    ],
    features: [
      "Conjunto com 3 anjos decorativos",
      "Diferentes cores e estilos",
      "Design infantil e delicado",
      "Acabamento de alta qualidade",
      "Ideal para decoração e presentes",
    ],
  },
  "nossa-senhora-luminaria": {
    id: 6,
    slug: "nossa-senhora-luminaria",
    name: "Nossa Senhora Luminária Decorativa",
    price: 85.0,
    oldPrice: 99.9,
    discount: 15,
    rating: 4.8,
    reviewCount: 9,
    stock: 6,
    description:
      "Elegante luminária decorativa em formato de Nossa Senhora. Uma peça única que combina devoção e funcionalidade, trazendo luz e paz para seu ambiente.",
    details:
      "Confeccionada em resina branca com acabamento fosco. Inclui iluminação interna com LED de baixo consumo e cabo com interruptor.",
    dimensions: "25cm de altura x 10cm de largura x 8cm de profundidade",
    material: "Resina com iluminação LED",
    weight: "0.7kg",
    sku: "NSL-024",
    categories: ["decoracao", "luminarias"],
    collections: ["nossa-senhora"],
    images: [
      "https://maededeus.vercel.app/public/nossa-senhora-luminaria.jpg",
      "https://maededeus.vercel.app/public/nossa-senhora-luminaria.jpg",
    ],
    features: [
      "Luminária decorativa",
      "Iluminação LED de baixo consumo",
      "Design elegante e minimalista",
      "Cabo com interruptor",
      "Ideal para criado-mudo, mesa de cabeceira ou altar",
    ],
  },
  "terco-sao-miguel": {
    id: 7,
    slug: "terco-sao-miguel",
    name: "Terço São Miguel Arcanjo em Madeira",
    price: 45.0,
    oldPrice: 55.0,
    discount: 18,
    rating: 4.9,
    reviewCount: 16,
    stock: 15,
    description:
      "Terço de São Miguel Arcanjo confeccionado em madeira com detalhes em azul. Uma peça especial para suas orações e devoção ao Príncipe da Milícia Celeste.",
    details:
      "Confeccionado com contas de madeira natural e cordão resistente em tom azul. Acompanha medalha de São Miguel Arcanjo.",
    dimensions: "45cm de comprimento",
    material: "Madeira e cordão",
    weight: "0.1kg",
    sku: "TSM-025",
    categories: ["tercos"],
    collections: ["sao-miguel"],
    images: [
      "https://maededeus.vercel.app/public/terco-sao-miguel-arcanjo.jpg",
      "https://maededeus.vercel.app/public/terco-sao-miguel-arcanjo.jpg",
    ],
    features: [
      "Contas de madeira natural",
      "Cordão em tom azul",
      "Medalha de São Miguel Arcanjo",
      "Acabamento artesanal",
      "Ideal para orações e devoção",
    ],
  },
  "cruz-face-cristo": {
    id: 8,
    slug: "cruz-face-cristo",
    name: "Cruz Face de Cristo em Resina",
    price: 59.9,
    oldPrice: 69.9,
    discount: 14,
    rating: 4.8,
    reviewCount: 11,
    stock: 9,
    description:
      "Cruz decorativa com a face de Cristo em relevo. Uma peça de arte sacra que representa o sacrifício e amor de Jesus, ideal para decorar seu lar com fé.",
    details:
      "Confeccionada em resina de alta qualidade com acabamento em branco. Inclui suporte para fixação na parede.",
    dimensions: "30cm de altura x 20cm de largura x 3cm de profundidade",
    material: "Resina",
    weight: "0.5kg",
    sku: "CFC-026",
    categories: ["decoracao", "cruzes"],
    collections: ["cruzes"],
    images: [
      "https://maededeus.vercel.app/public/cruz-face-de-cristo.jpg",
      "https://maededeus.vercel.app/public/cruz-face-de-cristo.jpg",
    ],
    features: [
      "Face de Cristo em relevo",
      "Acabamento em branco",
      "Design clássico e elegante",
      "Fácil instalação",
      "Símbolo de fé e devoção",
    ],
  },
}

